2024-09-03T02:18:33.079207-0400 ERROR ImportError: cannot import name 'remove_outliers' from 'preprocessing' (D:\Programming Projects\CAP\sentimental_cap_predictor\sentimental_cap_predictor\sentimental_cap_predictor\modeling\preprocessing.py)
2024-09-03T02:21:11.332798-0400 ERROR ImportError: cannot import name 'remove_outliers' from 'preprocessing' (D:\Programming Projects\CAP\sentimental_cap_predictor\sentimental_cap_predictor\sentimental_cap_predictor\modeling\preprocessing.py)
2024-09-07T16:10:28.848558-0400 ERROR Error during LNN model prediction: Shape of passed values is (689, 1), indices imply (14, 1)
2024-09-07T16:10:29.258539-0400 ERROR Traceback (most recent call last):
  File "D:\Programming Projects\CAP\sentimental_cap_predictor_v1.1\sentimental_cap_predictor\sentimental_cap_predictor\sentimental_cap_predictor\features.py", line 199, in generate_predictions
    future_df = pd.DataFrame(index=future_dates, data=predictions, columns=['LNN_Predictions'])
  File "C:\Users\phili\miniforge3\envs\sentimental_cap_predictor\lib\site-packages\pandas\core\frame.py", line 827, in __init__
    mgr = ndarray_to_mgr(
  File "C:\Users\phili\miniforge3\envs\sentimental_cap_predictor\lib\site-packages\pandas\core\internals\construction.py", line 336, in ndarray_to_mgr
    _check_values_indices_shape_match(values, index, columns)
  File "C:\Users\phili\miniforge3\envs\sentimental_cap_predictor\lib\site-packages\pandas\core\internals\construction.py", line 420, in _check_values_indices_shape_match
    raise ValueError(f"Shape of passed values is {passed}, indices imply {implied}")
ValueError: Shape of passed values is (689, 1), indices imply (14, 1)

2024-09-07T16:10:29.258539-0400 ERROR No result was generated.
2024-09-07T16:14:54.018720-0400 ERROR Error during LNN model prediction: Shape of passed values is (689, 1), indices imply (14, 1)
2024-09-07T16:14:54.019539-0400 ERROR Traceback (most recent call last):
  File "D:\Programming Projects\CAP\sentimental_cap_predictor_v1.1\sentimental_cap_predictor\sentimental_cap_predictor\sentimental_cap_predictor\features.py", line 198, in generate_predictions
    future_df = pd.DataFrame(index=future_dates, data=predictions, columns=['LNN_Predictions'])
  File "C:\Users\phili\miniforge3\envs\sentimental_cap_predictor\lib\site-packages\pandas\core\frame.py", line 827, in __init__
    mgr = ndarray_to_mgr(
  File "C:\Users\phili\miniforge3\envs\sentimental_cap_predictor\lib\site-packages\pandas\core\internals\construction.py", line 336, in ndarray_to_mgr
    _check_values_indices_shape_match(values, index, columns)
  File "C:\Users\phili\miniforge3\envs\sentimental_cap_predictor\lib\site-packages\pandas\core\internals\construction.py", line 420, in _check_values_indices_shape_match
    raise ValueError(f"Shape of passed values is {passed}, indices imply {implied}")
ValueError: Shape of passed values is (689, 1), indices imply (14, 1)

2024-09-07T16:14:54.031502-0400 ERROR No result was generated.
2024-09-07T16:17:41.442119-0400 ERROR Error during LNN model prediction: Shape of passed values is (689, 1), indices imply (14, 1)
2024-09-07T16:17:41.452687-0400 ERROR Traceback (most recent call last):
  File "D:\Programming Projects\CAP\sentimental_cap_predictor_v1.1\sentimental_cap_predictor\sentimental_cap_predictor\sentimental_cap_predictor\features.py", line 198, in generate_predictions
    future_df = pd.DataFrame(index=future_dates, data=predictions, columns=['LNN_Predictions'])
  File "C:\Users\phili\miniforge3\envs\sentimental_cap_predictor\lib\site-packages\pandas\core\frame.py", line 827, in __init__
    mgr = ndarray_to_mgr(
  File "C:\Users\phili\miniforge3\envs\sentimental_cap_predictor\lib\site-packages\pandas\core\internals\construction.py", line 336, in ndarray_to_mgr
    _check_values_indices_shape_match(values, index, columns)
  File "C:\Users\phili\miniforge3\envs\sentimental_cap_predictor\lib\site-packages\pandas\core\internals\construction.py", line 420, in _check_values_indices_shape_match
    raise ValueError(f"Shape of passed values is {passed}, indices imply {implied}")
ValueError: Shape of passed values is (689, 1), indices imply (14, 1)

2024-09-07T16:17:41.458169-0400 ERROR No result was generated.
2024-09-07T16:26:06.939829-0400 ERROR Error during LNN model prediction: Shape of passed values is (689, 1), indices imply (14, 1)
2024-09-07T16:26:06.953524-0400 ERROR Traceback (most recent call last):
  File "D:\Programming Projects\CAP\sentimental_cap_predictor_v1.1\sentimental_cap_predictor\sentimental_cap_predictor\sentimental_cap_predictor\features.py", line 198, in generate_predictions
    future_df = pd.DataFrame(index=future_dates, data=predictions, columns=['LNN_Predictions'])
  File "C:\Users\phili\miniforge3\envs\sentimental_cap_predictor\lib\site-packages\pandas\core\frame.py", line 827, in __init__
    mgr = ndarray_to_mgr(
  File "C:\Users\phili\miniforge3\envs\sentimental_cap_predictor\lib\site-packages\pandas\core\internals\construction.py", line 336, in ndarray_to_mgr
    _check_values_indices_shape_match(values, index, columns)
  File "C:\Users\phili\miniforge3\envs\sentimental_cap_predictor\lib\site-packages\pandas\core\internals\construction.py", line 420, in _check_values_indices_shape_match
    raise ValueError(f"Shape of passed values is {passed}, indices imply {implied}")
ValueError: Shape of passed values is (689, 1), indices imply (14, 1)

2024-09-07T16:26:06.961539-0400 ERROR No result was generated.
2024-09-07T16:30:59.934493-0400 ERROR Error during LNN model prediction: Shape of passed values is (689, 1), indices imply (14, 1)
2024-09-07T16:30:59.943467-0400 ERROR Traceback (most recent call last):
  File "D:\Programming Projects\CAP\sentimental_cap_predictor_v1.1\sentimental_cap_predictor\sentimental_cap_predictor\sentimental_cap_predictor\features.py", line 184, in generate_predictions
    future_df = pd.DataFrame(index=future_dates, data=predictions, columns=['LNN_Predictions'])
  File "C:\Users\phili\miniforge3\envs\sentimental_cap_predictor\lib\site-packages\pandas\core\frame.py", line 827, in __init__
    mgr = ndarray_to_mgr(
  File "C:\Users\phili\miniforge3\envs\sentimental_cap_predictor\lib\site-packages\pandas\core\internals\construction.py", line 336, in ndarray_to_mgr
    _check_values_indices_shape_match(values, index, columns)
  File "C:\Users\phili\miniforge3\envs\sentimental_cap_predictor\lib\site-packages\pandas\core\internals\construction.py", line 420, in _check_values_indices_shape_match
    raise ValueError(f"Shape of passed values is {passed}, indices imply {implied}")
ValueError: Shape of passed values is (689, 1), indices imply (14, 1)

2024-09-07T16:30:59.943467-0400 ERROR No result was generated.
2024-09-07T17:10:07.653432-0400 ERROR Error during LNN model prediction: "None of [Index(['Biased_Predictions'], dtype='object')] are in the [columns]"
2024-09-07T17:10:07.819518-0400 ERROR Traceback (most recent call last):
  File "D:\Programming Projects\CAP\sentimental_cap_predictor_v1.1\sentimental_cap_predictor\sentimental_cap_predictor\sentimental_cap_predictor\features.py", line 232, in generate_predictions
    'Biased_Predictions': scaler.inverse_transform(price_df[['Biased_Predictions']]).flatten(),  # Add biased predictions
  File "C:\Users\phili\miniforge3\envs\sentimental_cap_predictor\lib\site-packages\pandas\core\frame.py", line 4108, in __getitem__
    indexer = self.columns._get_indexer_strict(key, "columns")[1]
  File "C:\Users\phili\miniforge3\envs\sentimental_cap_predictor\lib\site-packages\pandas\core\indexes\base.py", line 6200, in _get_indexer_strict
    self._raise_if_missing(keyarr, indexer, axis_name)
  File "C:\Users\phili\miniforge3\envs\sentimental_cap_predictor\lib\site-packages\pandas\core\indexes\base.py", line 6249, in _raise_if_missing
    raise KeyError(f"None of [{key}] are in the [{axis_name}]")
KeyError: "None of [Index(['Biased_Predictions'], dtype='object')] are in the [columns]"

2024-09-07T17:10:07.821705-0400 ERROR No result was generated.
2024-09-08T01:22:27.421319-0400 ERROR Failed to extract features for AAPL: 'str' object has no attribute 'empty'
2024-09-08T01:22:37.667900-0400 ERROR Failed to extract features for GOOGL: 'str' object has no attribute 'empty'
2024-09-08T01:33:14.605128-0400 ERROR Failed to extract features for MSFT: 'str' object has no attribute 'empty'
2024-09-08T01:36:08.280556-0400 ERROR Failed to extract features for NVDA: 'str' object has no attribute 'empty'
2024-09-08T01:36:18.636586-0400 ERROR Failed to extract features for AMD: 'str' object has no attribute 'empty'
2024-09-08T01:42:40.899232-0400 ERROR Failed to extract features for JNJ: 'str' object has no attribute 'empty'
2024-09-08T01:49:13.405756-0400 ERROR Failed to extract features for PFE: 'str' object has no attribute 'empty'
2024-09-08T01:53:42.299597-0400 ERROR Failed to extract features for MRK: 'str' object has no attribute 'empty'
2024-09-08T01:55:03.646742-0400 ERROR Failed to extract features for UNH: 'str' object has no attribute 'empty'
2024-09-08T01:56:21.689594-0400 ERROR Failed to extract features for ABT: 'str' object has no attribute 'empty'
2024-09-08T01:57:28.124268-0400 ERROR Failed to extract features for JPM: 'str' object has no attribute 'empty'
2024-09-08T01:59:37.508512-0400 ERROR Failed to extract features for BAC: 'str' object has no attribute 'empty'
2024-09-08T01:59:38.025206-0400 ERROR Failed to extract features for GS: 'str' object has no attribute 'empty'
2024-09-08T02:01:03.638330-0400 ERROR Failed to extract features for WFC: 'str' object has no attribute 'empty'
2024-09-08T02:02:29.135392-0400 ERROR Failed to extract features for AXP: 'str' object has no attribute 'empty'
2024-09-08T02:04:38.855749-0400 ERROR Failed to extract features for TSLA: 'str' object has no attribute 'empty'
2024-09-08T02:05:50.584677-0400 ERROR Failed to extract features for AMZN: 'str' object has no attribute 'empty'
2024-09-08T02:07:26.288962-0400 ERROR Failed to extract features for NKE: 'str' object has no attribute 'empty'
2024-09-08T02:07:26.778858-0400 ERROR Failed to extract features for HD: 'str' object has no attribute 'empty'
2024-09-08T02:09:09.184417-0400 ERROR Failed to extract features for MCD: 'str' object has no attribute 'empty'
2024-09-08T02:09:10.726462-0400 ERROR Failed to extract features for PG: 'str' object has no attribute 'empty'
2024-09-08T02:09:11.679507-0400 ERROR Failed to extract features for KO: 'str' object has no attribute 'empty'
2024-09-08T02:10:49.586154-0400 ERROR Failed to extract features for PEP: 'str' object has no attribute 'empty'
2024-09-08T02:11:55.463391-0400 ERROR Failed to extract features for WMT: 'str' object has no attribute 'empty'
2024-09-08T02:15:15.087779-0400 ERROR Failed to extract features for COST: 'str' object has no attribute 'empty'
2024-09-08T02:15:15.641619-0400 ERROR Failed to extract features for BA: 'str' object has no attribute 'empty'
2024-09-08T02:18:30.117517-0400 ERROR Failed to extract features for CAT: 'str' object has no attribute 'empty'
2024-09-08T02:20:08.341850-0400 ERROR Failed to extract features for UPS: 'str' object has no attribute 'empty'
2024-09-08T02:20:09.163312-0400 ERROR Failed to extract features for GE: 'str' object has no attribute 'empty'
2024-09-08T02:21:58.136199-0400 ERROR Failed to extract features for MMM: 'str' object has no attribute 'empty'
2024-09-08T13:01:19.338595-0400 ERROR An error occurred in the main function: '<' not supported between instances of 'Timestamp' and 'str'
2024-09-08T13:01:19.671642-0400 ERROR Traceback (most recent call last):
  File "D:\Programming Projects\CAP\sentimental_cap_predictor_v1.1\sentimental_cap_predictor\sentimental_cap_predictor\sentimental_cap_predictor\features.py", line 276, in <module>
    result = generate_predictions(price_df, news_df, ticker, mode, prediction_days)
  File "D:\Programming Projects\CAP\sentimental_cap_predictor_v1.1\sentimental_cap_predictor\sentimental_cap_predictor\sentimental_cap_predictor\features.py", line 228, in generate_predictions
    df_final = merge_data(existing_df, df_final, merge_on='Date')
  File "D:\Programming Projects\CAP\sentimental_cap_predictor_v1.1\sentimental_cap_predictor\sentimental_cap_predictor\sentimental_cap_predictor\features.py", line 50, in merge_data
    merged_df = pd.concat([existing_df, new_df]).drop_duplicates(subset=[merge_on]).sort_values(by=merge_on).reset_index(drop=True)
  File "C:\Users\phili\miniforge3\envs\sentimental_cap_predictor\lib\site-packages\pandas\core\frame.py", line 7200, in sort_values
    indexer = nargsort(
  File "C:\Users\phili\miniforge3\envs\sentimental_cap_predictor\lib\site-packages\pandas\core\sorting.py", line 439, in nargsort
    indexer = non_nan_idx[non_nans.argsort(kind=kind)]
TypeError: '<' not supported between instances of 'Timestamp' and 'str'

2024-09-08T13:09:19.857149-0400 ERROR Failed to extract features for AAPL: 'str' object has no attribute 'empty'
2024-09-08T13:10:17.438831-0400 ERROR Failed to extract features for GOOGL: 'str' object has no attribute 'empty'
2024-09-08T13:17:45.450924-0400 ERROR Failed to extract features for AAPL: 'str' object has no attribute 'empty'
2024-09-08T13:18:42.533658-0400 ERROR Failed to extract features for GOOGL: 'str' object has no attribute 'empty'
2024-09-08T13:26:07.899396-0400 ERROR Failed to extract features for AAPL: 'str' object has no attribute 'empty'
